# Contains the schema of the data

COLUMNS:
  gender: str
  SeniorCitizen: int64
  Partner: str
  Dependents: str
  tenure: int64
  PhoneService: str
  MultipleLines: str
  InternetService: str
  OnlineSecurity: str
  OnlineBackup: str
  DeviceProtection: str
  TechSupport: str
  StreamingTV: str
  StreamingMovies: str
  Contract: str
  PaperlessBilling: str
  PaymentMethod: str
  MonthlyCharges: float64
  TotalCharges: str

TARGET_COLUMN:
  name: Churn